# Generated by Django 5.0.6 on 2024-08-25 11:43

import base.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiresAt', models.DateTimeField()),
                ('code', models.CharField(default=base.models.MagicLink.generate_code, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='magic_link',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.magiclink'),
        ),
    ]
