# Generated by Django 5.0.6 on 2024-07-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_order_name_shippingaddress_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/default_image.PNG', null=True, upload_to=''),
        ),
    ]
